import React from 'react'

export default function TermsConditions() {
  return (
    <div>
      <section className=" policies_policy__SAyW_ pb8"><div className=" weblayout_container__0W9V9">
        <h1>TERMS AND CONDITIONS</h1>
        <div className="policies_tableContent__ED8ag">
      <h2 className="policies_tableContent-heading__5U2l6">General Privacy Terms</h2>
      <ol type="A">
        <li><a href="#about">About ScholarSense and the Platform</a></li>
        <li><a href="#platform">Platform Services</a></li>
        <li><a href="#right">Right to Access and Account Creation</a></li>
        <li><a href="#subscription">Subscription Terms</a></li>
        <li><a href="#use">Use of the Platform</a></li>
        <li><a href="#user">User-generated Content and Ownership</a></li>
        <li><a href="#conduct">Your Conduct on the Platform</a></li>
        <li><a href="#feedback">Feedback</a></li>
        <li><a href="#claim">Claims against User-generated Content and use of third-party intellectual property</a></li>
        <li><a href="#right">ScholarSense’s Rights</a></li>
        <li><a href="#communication">Communications</a></li>
        <li><a href="#personal">Processing of Personal Information</a></li>
        <li><a href="#availability">Platform Availability</a></li>
        <li><a href="#deletion">Deletion of Account</a></li>
        <li><a href="#disclaimer">Disclaimer</a></li>
        <li><a href="#limitation">Limitation of Liability</a></li>
        <li><a href="#Indemnity">Indemnity and Release</a></li>
        <li><a href="#ofac">OFAC (Office of Foreign Asset Control)</a></li>
        <li><a href="#civil">California Civil Code Section 1789.3</a></li>
        <li><a href="#law">Applicable Laws and Jurisdiction</a></li>
        <li><a href="#provision">General Provisions</a></li>
        <li><a href="#support">Contact for User Support/Queries</a></li>
        <li><a href="#consumer">Consumer Grievances</a></li>
        <li><a href="#contact">Contact Us</a></li>
      </ol>
    </div>
    <p>Welcome to ScholarSense We hope that you have a great experience using our Platform. </p>
    <p>
      Platform Terms are an electronic record under the Information Technology Act, 2000, the Information Technology (Amendment) Act, 2008, and other such applicable laws and regulations applicable to electronic records (including any federal laws), as introduced/amended from time to time and is generated by a computer system; as such, the Platform Terms does not require any physical, electronic, or digital signature. Your acceptance of the Platform Terms forms a legally binding agreement between you and ScholarSense <strong>(“Agreement”)</strong>. Hence, please take your time to read the Platform Terms in their entirety.
    </p>
    <p>These Terms and Conditions apply to all users of the Platform, including without limitation, all persons who create and / or make available Content Provider Content ( as defined under the <strong>‘Intellectual Property’</strong> section below) on the Platform (referred to as <strong>“Content Providers”</strong>) and users who access the Platform to learn a subject or a skill (referred to as <strong>“Learners”</strong>) or users who access the Platform otherwise (collectively referred to as <strong>“you”</strong>,<strong> “your”</strong>, or<strong> “User(s)”</strong>). The relationship between you and ScholarSense is defined by these Terms and Conditions along with the <a href="privacy-policy">Privacy Policy</a>, <a href="refund-policy">Refund Policy</a>, <a href="cookies-policy">Cookies Policy</a>, the <a href="/user-guidelines">User Guidelines</a> and any other terms and conditions, rules, policies or guidelines included in these Terms and Conditions or <a href="privacy-policy">Privacy Policy</a> by reference and/or as updated on the Platform or otherwise communicated to you from time to time (including terms and conditions of other third party platforms that may be used or accessed for gaining access to the Platform or using the Services on the Platform (collectively referred to as the <strong>“Platform Term(s)”</strong>). The Platform Terms shall govern your use of the Platform and the Services (defined below) offered therein. Your access to the Platform is subject to your acceptance of the Platform Terms.</p>
    <p>Platform Terms are an electronic record under the Information Technology Act, 2000, the Information Technology (Amendment) Act, 2008, and other such applicable laws and regulations applicable to electronic records (including any federal laws), as introduced/amended from time to time and is generated by a computer system; as such, the Platform Terms does not require any physical, electronic, or digital signature. Your acceptance of the Platform Terms forms a legally binding agreement between you and ScholarSense <strong>(“Agreement”)</strong>. Hence, please take your time to read the Platform Terms in their entirety.</p>
    <div className="pt7" id="about">
      <h2 className="">About ScholarSense</h2>
      <p>
        <strong>ScholarSense </strong>Private Limited, a company incorporated under the (Indian) Companies Act, 2013, having its corporate office at Plot No. A 12, IT Park, Chandigarh- 160101, India <strong>(“ScholarSense India”)</strong>. In any jurisdiction other than India, wherever Services are rendered through the Platform, the same is offered by ScholarSense India and / or its affiliates (as relevant pursuant to appropriate intra group contractual arrangements). For knowing with which entity of your Agreement will be, please refer the list in<strong> Annexure A </strong>below.
      </p>
    </div>
    <div className="pt7" id="platform">
      <h2 className="">Platform Services</h2>
      <p>
        ScholarSense Platform is an online service platform enabling Content Providers to create and offer content in various formats including without limitation audiovisuals, audio, pre-recorded audiovisuals, live audiovisuals and/or in written form in a diverse range of categories through various modes and means <strong>(“Content Provider Content”)</strong> and publish and make available such Content Provider Content to the Learners. ScholarSense acts as an intermediary between the Content Providers and Learners [in accordance with the Information Technology Act, 2000, or the Digital Millennium Copyright Act (as amended from time to time)] or other equivalent / similar legislations and makes available the Content Provider Content to the Learners, including through subscription offerings (refer to the Subscription Terms below to know more). ScholarSense may also offer, either directly or indirectly (through other third party platforms), other incidental and ancillary services which may include without limitation question banks, mock tests, doubt-solving solutions, live mentorship live videos, contests, scholarships, webinars and events (physical and/or online) and facilitating discussion forums.
        <br />
        Further, ScholarSense may offer certain products/services to you in collaboration with one or more of the Group Platforms (as defined under the <a href="privacy-policy">Privacy Policy</a>). In such cases, to the extent that such product/services are made available to you through the Platform, the Platform Terms shall continue to apply to you.
        <br />
        For the purpose of the Platform Terms, usage of the terms<strong>“Platform Services”/ “Services”</strong> shall mean and include all the services referred to in this section and such other products or services as may be offered by ScholarSense.
        <br />
        You agree and acknowledge that ScholarSense shall have the right at any time to change or discontinue any Service, product, aspect, or feature of the Platform, including without limitation to, the User-generated Content (to the extent it is permitted to, or required, by virtue of being an ‘intermediary’), its availability and Supported/Compatible device required to access or use the Services. ScholarSense reserves the right to terminate your Subscription and / or restrict your access to the Platform, if you choose not to provide / partially provide the requested information and/or fail to adhere to the Platform Terms.
      </p>
    </div>
    <div className="pt7" id="right">
      <h2 className="">Right to Access and Account Creation</h2>
      <p>
        As a Learner, to access the Platform and use certain Services, you will be required to register and create an account on the Platform by providing the requested details.
        <br />
        To access and register on the ScholarSense Platform you must meet the ‘Age Requirements’ specified hereinbelow. By using the ScholarSense Platform, you, through your actions, affirm that the Age Requirements are met- by you.
        <br />
        You can register on the Platform for free however, certain Services offered on the Platform may be chargeable. Please review the Service offerings on our Site or Application(s). You are not obligated to purchase any product or use any Service offered on the Platform.
      </p>
      <ul type="disc">
        <strong>Age Requirements to register and use on the Platform (“Age Requirements”):</strong>
        <li>If you are a resident of India or any other country (except USA, UK or EU countries), then you must have attained at least 18 (eighteen) years of age to register and use the ScholarSense Platform;</li>
        <li>If you are a resident of the European Union (EU) country and have attained at least 16 (sixteen) years of age, then you are permitted to register and use the ScholarSense Platform; and</li>
        <li>If you are a resident of the United States of America (USA) or United Kingdom (UK) and have attained at least 13 (thirteen) years of age, then you can register and use the ScholarSense Platform.</li>
        <li>If you are a resident of the US, UK or EU countries and are between the ages 13 and 18/16 and 18 respectively or if you are resident of any other country and are considered to be of any age determined for use of internet services but are less than the contractual age determined by the applicable laws of such country, then by using the Platform, you confirm to us that your use of the Platform is with the permission of your Parent(s) (as defined below), and your Parent has read, agreed and accepted to the Agreement; and in the event of any dispute between you and ScholarSense pursuant to your Agreement with us, the terms of our Agreement shall be applicable to and enforceable against your Parent.</li>
      </ul>
      <p>
        A Learner who does not fulfill the Age Requirements mentioned above (as may be revised as per applicable laws from time to time) and is desirous of registering on the Platform i.e., if a Learner is a <strong>“Minor”/ “Child”</strong>, then the Learner may use the Platform with the consent of, and under the supervision of, their parent or legal guardian <strong>(“Parent”)</strong>. Accordingly, in such a case, the Parent must register for the Minor and agree to the Platform Terms at the time of their registration on the Platform. Please note that Minors/Children are not by themselves eligible to register on the Platform. When a Minor/Child uses the Platform, we assume that the Parent of such Minor/Child has enabled the Minor/Child's usage of the Platform by agreeing to the Platform Terms and that such usage is under the supervision of their Parent.
        <br />
        ScholarSense reserves the right to terminate your Subscription and / or restrict your access to the Platform, if it is discovered that you do not meet the Age Requirements and/or the consent to register and use the Platform is not obtained as stated above. You acknowledge that ScholarSense does not have the responsibility to ensure that You conform to the aforesaid Age Requirements. It shall be your sole responsibility to ensure that the required qualifications are met.
        <br />
        If you are a Content Provider, your access and use of the Platform may additionally be subject to separate agreement(s) with ScholarSense and shall be collectively governed by the terms of such agreement, the Terms and Conditions, other Platform Terms, and such other terms as may be communicated or agreed with you from time to time.
        <br />
        You are responsible for maintaining the confidentiality of your account and password to access the Platform. You acknowledge that your account is personal to you and agree not to provide any other person with access to the Platform and to restrict access to your device to prevent any unauthorized access to your account. You agree to accept responsibility for all activities that occur under your account. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your username, password, or other Personal Information. You should take all necessary steps to ensure that the password is kept confidential and secure at all times, and if you have any reason to believe that your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner, you agree to immediately change your password or inform us of any unauthorized access to or use of your username or password, so that we are able to help you stop or prevent such unauthorized access. Please ensure that the details you provide us are correct and complete.
        <br />
        You represent that the information provided by you at the time of the registration are correct, true, and accurate, and you agree to update the same as and when there is any change in the said information. Please read our <a href="privacy-policy">Privacy Policy</a> to understand how we handle your information.
        <br />
        Please note that we reserve the right to reject or put on-hold your registration on the Platform as may be required to comply with any legal and regulatory provisions, and also reserve the right to refuse access to the Platform, terminate accounts, remove content at any time without providing any notice to you, and/or reserve the right to disable any account, feature, or identifiers, whether chosen by you or provided by us, at any time if, in our opinion, any information provided by you violates or you have violated any provision of the Platform Terms or any applicable law or government policies.
        <br />
        Further, to access the Platform, create, publish and/or view the User-generated Content on the Platform, you will need to use a <strong>"Supported/Compatible Device"</strong> which means a personal computer, mobile phone, portable media player, or other electronic device that meets the system and compatibility requirements and on which you are authorized to operate the Platform. The Supported/Compatible Devices to access the Platform and/or avail the Services may change from time to time and, in some cases, whether a device is (or remains) a Supported/Compatible Device may depend on software or systems provided or maintained by the device manufacturer or other third parties. Accordingly, devices that are Supported/Compatible Devices at one time may cease to be Supported/Compatible Devices in the future. Thus, kindly make sure that the device that you use is compatible with our system/software to use the Platform and avail the Services offered therein.
      </p>
    </div>
    <div className="pt7" id="subscription">
      <h2 className="">Subscription Terms</h2>
      <p>
        For Learners, ScholarSense does not charge any fee for registration and account creation. However, certain Services offered by ScholarSense may be chargeable. Accordingly, access to certain Services and features is offered by ScholarSense through a multi-tiered paid subscription plan(s) or purchases; the details of the Services and applicable features along with their corresponding prices can be found on our <a href="https://www.ScholarSense.com">Site</a> and/or Application <strong>(“Subscription”/ “Subscription Service”)</strong>. You can purchase Subscriptions by following the instructions you encounter as you navigate through the Platform.
      </p>
      <ol type="decimal">
        <li>
          The terms that are applicable to Your purchase of Subscription(s) –
          <ol type="a">
            <li>
              Purchase of a Subscription will allow you access only to the content available under the category of content for which you have purchased the Subscription.
            </li>
            <li>
              The Services offered, and the validity/term of your Subscription <strong>(“Subscription Period”)</strong> may vary depending on the plan you may purchase. Hence, before you proceed to purchase any Subscription, please read and understand the details of the Subscription(s) you intend to purchase on the Platform. If you are unclear about any part of the Subscription offering or need further clarification, then, prior to your purchase, please feel free to write to us at the email address provided in the ‘Contact for User Support/Queries’ section below.
            </li>
            <li>
              We may personalize Services and feature them as part of Subscriptions, including showing you recommendations on content in the subscribed category, and other related categories that might be of interest to you. We also endeavor to continuously improve the Subscription offerings to improve your Platform experience.
            </li>
            <li>
              Subscription Period may be extended upon renewal of your already purchased Subscription. The terms of renewal, if any, can be found on our <a href="https://www.ScholarSense.com">Site</a> and/or Application. However, please note that the prices may stand revised from the time of your first purchase of the Subscription.
            </li>
            <li>
              The Subscription is of a personal nature and is solely for the benefit of the person subscribing and is not allowed to be resold by you or transferred to or shared with any other person for consideration or otherwise. In the event we get to know that any User has resold / transferred / shared Subscription with another person, then ScholarSense retains the right to cancel/terminate the Subscription forthwith.
            </li>
            <li>
              Owing to various factors, including any limitations by contract, Content Providers may change from time-to-time and as a mere platform provider, ScholarSense cannot guarantee the continued services of any Content Provider.
            </li>
            <li>
              Due to the limitations, if any, imposed on us by our Content Providers (who own the Content Provider Content), the Content Provider Content we make available to you under any Subscription offering are subject to restrictions on viewing access and on the length of time we make them available to you. These restrictions may change over time as we add new features, devices, and content to our Subscription Service. Illustratively, following are some of the restrictions that are applicable to your access to the content (made available through Subscription Service or otherwise):
              <ol type="a">
                <li>
                  <strong>Live – Streaming of Content Provider Content/ Live Videos:</strong> You will get access to attend live videos (in other words, live- streamed content), if the same is offered as part of your purchased Subscription. The access shall be available to you through the Platform during the Subscription Period and shall be subject to the Platform Terms. Please be sure to use a Supported/Compatible device (refer to the ‘Right to Access and Account Creation’ section above) while accessing the live videos.
                </li>
                <li>
                  <strong>Viewing Period:</strong> Depending on the Subscription, we may make available the pre-recorded videos and/or recorded versions of any relevant live video to you for continued viewing on the Platform (which may include in-app downloading as mentioned below) during your Subscription Period. Please note that availability of the recorded videos and/or the recorded versions of any relevant live video content for your subsequent access on the Platform is subject to our agreements with the Content Providers, and we do not in any manner guarantee the availability of the same for any reason whatsoever.
                </li>
                <li>
                  <strong>In-App Downloading:</strong> Depending upon your Subscription, you may only have an option to do in-app downloads and the downloaded content can be viewed by you during the Subscription Period. After downloading the Content Provider Content, you shall have access to the same for the Subscription Period only and all access to the downloaded content shall be removed on expiry or termination of your Subscription, as the case maybe.
                </li>
                <li>
                  <strong>Quality of Streaming:</strong> The resolution and quality of the content you receive will depend on several factors, including the type of Compatible Device on which you are accessing the Content Provider Content and your bandwidth, which may increase or decrease over the course of your viewing. While we strive to provide you a high-quality viewing experience, we make no guarantee as to the resolution or quality of the content you will see when streaming.
                </li>
              </ol>
            </li>
            <li>
              Depending on the Subscription Service you have purchased, you may be given access to certain additional Services and features. The additional terms applicable to each of these additional Services may be made available to you on the Platform in the form of terms and conditions or FAQs (Frequently Asked Questions) for that specific Service or may be otherwise communicated to you. Hence, please be sure to go through the Platform Terms to understand the additional services, if any made available to you, and how you can avail the same.
            </li>
          </ol>
        </li>
      </ol>
    </div>
        </div>
        </section>
    </div>
  )
}
